name: build-dotnet-gdriveauthtool

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    name: Build and publish GDriveAuthTool
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            rid: win-x64
          - os: ubuntu-latest
            rid: linux-x64
          - os: macos-latest
            rid: osx-x64
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore
        run: |
          dotnet restore "CorporateWebsite/languages/dotnet/GDriveAuthTool/GDriveAuthTool.csproj"

      - name: Build
        run: |
          dotnet build "CorporateWebsite/languages/dotnet/GDriveAuthTool/GDriveAuthTool.csproj" -c Release --no-restore

      - name: Publish
        run: |
          dotnet publish "CorporateWebsite/languages/dotnet/GDriveAuthTool/GDriveAuthTool.csproj" -c Release -r ${{ matrix.rid }} --self-contained false --no-restore

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: GDriveAuthTool-${{ matrix.rid }}-${{ github.ref_name }}
          path: CorporateWebsite/languages/dotnet/GDriveAuthTool/bin/Release/net9.0/${{ matrix.rid }}/publish/**

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          tag_name: ${{ github.ref_name }}
          name: GDriveAuthTool ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: |
            artifacts/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
