name: Slack Notifications

on:
  workflow_run:
    workflows: [ "CI - Multi-language build & test", "CodeQL" ]
    types:
      - completed

jobs:
  notify:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion != 'success' }}
    steps:
      - name: Notify Slack
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ github.event.workflow_run.conclusion }}
          fields: repo,message,commit,author
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
